# Build and publish the dockerfile
name: publish
on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GH container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # We use fossabot as the publisher
          # This means that fossabot is the only actor which can update the dockerfile through automation
          # This prevents other PR's from publishing out-of-date images.
          password: ${{ secrets.FOSSABOT_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: 'haskell-dev-tools:8.10.4'
          push: true
          context: ./src
